url: "https://adilima.github.io"
baseurl: "/paladin-in-violent-winds"

title: Pahlawan Di Tengah Badai
author:
  name: FX. Adi Lima
  email: adi7598@gmail.com

description: >
  Kumpulan cerita silat dan sejarah di era Dinasti Yuan,
  bukan hanya di seputar Tiongkok kuno, tetapi juga bisa
  menceritakan negara-negara lain di sekitarnya. Goryeo (Korea) 
  di jaman itu adalah bagian dari Dinasti Yuan. Negara-negara seperti 
  Khwaresmia, Kazakhstan, Uzbekistan, Turkmenistan, Afghanistan, 
  India, Nepal, Tibet, dsb — semuanya adalah negara yang mengakui 
  kedaulatan Dinasti Yuan.


